### ISSUE TITLE
Unexpected xmlns:xsi attribute in top-level structs

### ISSUE THREAD

**Issue by ShadowJonathan** [AS207960/xml-serde#3]
When i was working on making this library work with libvirt XML documents (as it seems this library is the only one which supports namespaces and attributes across rust's xml libraries), I got the following attribute automatically injected in top-level structs;

`xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"`

While i understand this is useful for some generic XML usecases, i think that for a serde library, it shouldn't inject unexpected or potentially colliding data into structures, especially if there's no way to turn it off.

So im recommending to maybe defer this to a `#[xml(inject(xsi = 2001))]` container, variant, and field attribute (described [here](https://serde.rs/attributes.html)) to let developers decide if such a namespace declaration is useful for their project.

**Comment by TheEnbyperor** [comment]
Agreed, the inclusion of the XSI xmlns should be optional, I'll add a configuration option for that.

**Comment by TheEnbyperor** [comment]
Just pushed version `1.1.0` to crates, that has a `include_schema_location` option now.

**Comment by ShadowJonathan** [comment]
Thanks, then i think this can be closed.
